### ISSUE TITLE
ModuleNotFoundError: No module named 'botocore.vendored'

### ISSUE THREAD

**Issue by yrdeboer** [terrycain/aioboto3#171]
* Async AWS SDK for Python version:
* Python version: 3.6.3
* Operating System: Ubuntu 18.10

### Description

Hi, first of all, AWESOME that someone actually did the effort to make this stuff async!!

I'm using:

python 3.6.3
aioboto3==6.3.0
aiobotocore==0.10.2
awscli==1.16.26
boto3==1.9.91
botocore==1.12.16

But this does not work with the latest botocore version (which has no module "vendored" needed by aiobotocore.endpoint).

I've been fiddling with versions for almost an hour now and I can't get it right. Pip neither ;(

Could you please share a working version set?

```
Traceback (most recent call last):
  File "encryption.py", line 3, in <module>
    import aioboto3
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aioboto3/session.py", line 8, in <module>
    import aiobotocore.session
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/__init__.py", line 1, in <module>
    from .session import get_session, AioSession
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/session.py", line 8, in <module>
    from .client import AioClientCreator
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/client.py", line 11, in <module>
    from .args import AioClientArgsCreator
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/args.py", line 9, in <module>
    from .endpoint import AioEndpointCreator
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 14, in <module>
    from botocore.vendored.requests.structures import CaseInsensitiveDict
ModuleNotFoundError: No module named 'botocore.vendored'
```

**Comment by yrdeboer** [comment]
I actually tried to import CaseInsensitiveDict from requests, but then I ran into another error:

```

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 956, in get_component
    return self._components[name]
KeyError: 'config_store'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "encryption.py", line 8, in <module>
    KMS_CLIENT = aioboto3.client('kms', region_name='eu-west-1')
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aioboto3/__init__.py", line 65, in client
    return _get_default_session(loop=loop).client(*args, **kwargs)
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/ntfs/projects/gsmg/venv3.6/lib/python3.6/site-packages/aiobotocore/session.py", line 72, in create_client
    config_store = self.get_component('config_store')
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 733, in get_component
    return self._components.get_component(name)
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 958, in get_component
    raise ValueError("Unknown component: %s" % name)
ValueError: Unknown component: config_store

```

**Comment by terrycain** [comment]
Ok when I just installed only `aioboto3==6.3.0` in a virtualenv I got the below. `aioboto3` will bring in the required compatible aiobotocore, boto3 and botocore dependencies. 

Your botocore version is older than what I have so i would assume that is to blame. If your using a requirements file to pip install your dependencies then i would only target `aioboto3`, that will pull in the rest.

```
aioboto3==6.3.0
aiobotocore==0.10.2
aiohttp==3.5.4
async-generator==1.10
async-timeout==3.0.1
attrs==19.1.0
boto3==1.9.91
botocore==1.12.91
chardet==3.0.4
docutils==0.14
idna==2.8
idna-ssl==1.1.0
jmespath==0.9.4
multidict==4.5.2
pkg-resources==0.0.0
python-dateutil==2.8.0
s3transfer==0.2.1
six==1.12.0
typing-extensions==3.7.2
urllib3==1.24.3
wrapt==1.11.1
yarl==1.3.0

```

**Comment by yrdeboer** [comment]
Thank you, it did not work, but I saw that there were distribution packages installed that interfered.

I'm using boto3 for encryption/decryption in an asynchronous environment.

Do you have plans to support KMS?

I'll be looking into that eventually, so if you want, I could probably do it myself and propose a merge request, though my AWS knowledge is (very) poor.

**Comment by terrycain** [comment]
Ahh you should really install aioboto3 in a virtual environment, that would have solved all of this.

Yeah is supports anything boto3 does. There are some odd edge cases with resources but generally anything boto3.client() supports this will support also.
