### ISSUE TITLE
RuntimeError: Event loop is closed with Chalice / Lambda

### ISSUE THREAD

**Issue by toleabivol** [terrycain/aioboto3#185]
* Async AWS SDK for Python version: 6.4.1
* Python version: 3.7.2
* Operating System: Windows 7 / Lambda python 3.7

### Description

Running aioboto3 with chalice (flusk for aws) / lambda. On local it always runs in the same runtime (script does not restart after each call to the api) but in lambda it happens sometimes because even though it is stateless sometimes aws internals will reuse the same instances. See https://stackoverflow.com/a/59309521/2470346 .

The problem is that aioboto3 stores the session in global and while it works for the first call it will not work for the second and other following calls as it tries to reuse the same session - therefore the same loop that already got closed.

### What I Did

```python
import asyncio
import aioboto3
from chalice import Chalice

app = Chalice(app_name="test")
@app.route('/v1/test', methods=['GET'])
def test():
    asyncio.run(test_main_coroutine())
    return {
        "foo": "bar",
    }

async def test_main_coroutine()
    return "lala"

```

### Workaround
In the main coroutines, reset the default session and force it to use the new loop:
```python
# rewrite aioboto default session so it uses a new one on each api call and not the global one on first run
async def test_main_coroutine()
    aioboto3.setup_default_session()
```

### How it should've worked
I think aioboto3 should use the new loop on each call. This means it should not store the loop in the session or always try to get the running loop.

### Trace

```
Traceback (most recent call last):
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\chalice\app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "C:\Users\abivol\repos\venvname\src\chalice\app.py", line 122, in get_brochure
    response = asyncio.run(get_brochure_main_coroutine(config_id))
  File "C:\python37\Lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\python37\Lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\abivol\repos\venvname\src\chalice\app.py", line 139, in get_brochure_main_coroutine
    config_to_trunk = await get_config_to_trunk(BUCKET, config_id, raise_error=True)
  File "C:\Users\abivol\repos\venvname\src\chalice\chalicelib\utilities.py", line 42, in get_config_to_trunk
    config_to_trunk = await s3_fetch_json(bucket, get_config_to_trunk_key_name(config_id))
  File "C:\Users\abivol\repos\venvname\src\chalice\chalicelib\aws_utilities.py", line 67, in s3_fetch_json
    await s3_get(bucket, key, data)
  File "C:\Users\abivol\repos\venvname\src\chalice\chalicelib\aws_utilities.py", line 46, in s3_get
    return await s3.download_fileobj(bucket, key, filelike)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aioboto3\s3\inject.py", line 77, in download_fileobj
    resp = await self.get_object(Bucket=Bucket, Key=Key)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\client.py", line 89, in _make_api_call
    operation_model, request_dict, request_context)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\client.py", line 110, in _make_request
    request_dict)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\endpoint.py", line 76, in _send_request
    exception):
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\endpoint.py", line 178, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\endpoint.py", line 139, in _do_get_response
    http_response = await self._send(request)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiobotocore\endpoint.py", line 220, in _send
    request.method, url=url, headers=headers_, data=data, proxy=proxy)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aiohttp\connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "C:\python37\Lib\asyncio\tasks.py", line 769, in shield
    inner = ensure_future(arg, loop=loop)
  File "C:\python37\Lib\asyncio\tasks.py", line 581, in ensure_future
    task = loop.create_task(coro_or_future)
  File "C:\python37\Lib\asyncio\base_events.py", line 403, in create_task
    self._check_closed()
  File "C:\python37\Lib\asyncio\base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by terrycain** [comment]
Currently it exhibits the same behaviour that boto3 uses, at the moment I'm undecided if I want to deviate from that mode of operation.

**Comment by vishalkuo** [comment]
I believe that I ran into the same issue here regarding unit tests with pytest. The issue was that I had two dynamodb tests in a row and the first one passed and the second one failed.

```
../../.virtualenvs/bonfire/lib/python3.8/site-packages/aiohttp/connector.py:964: in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py:860: in shield
    inner = ensure_future(arg, loop=loop)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py:661: in ensure_future
    task = loop.create_task(coro_or_future)
uvloop/loop.pyx:1394: in uvloop.loop.Loop.create_task
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   RuntimeError: Event loop is closed
```

I believe the solution for me was similar:
```python3
@pytest.fixture(scope="function", autouse=True)
async def setup_aioboto3() -> None:
    aioboto3.setup_default_session()
```

but ideally we wouldn't have to do this

**Comment by vishalkuo** [comment]
Bump on this

**Comment by terrycain** [comment]
Check out the test fixtures here - https://github.com/terrycain/aioboto3/blob/master/tests/conftest.py#L64-L232 does that help?

**Comment by waffleshop** [comment]
You cannot use `asyncio.run()` within AWS Lambda; it will close the event loop after executing the target function. You can resolve your issue by updating the following line
```
asyncio.run(test_main_coroutine())
```
to
```
asyncio.get_event_loop.run_until_complete(test_main_coroutine())
```

**Comment by DrBomb** [comment]
Running the following code
```
async def main2():
    async with aioboto3.client('iot-data') as client:
        result = await client.get_thing_shadow(thingName=configs[1][0])
        print(await result['payload'].read())

if __name__ == "__main__":
    asyncio.run(main2())
```

Will result on the payload being printed, which is great. But the exception is still thrown. What should I do to close aioboto3 cleanly?

I'm not using Lambda, running python directly

**Comment by terrycain** [comment]
9.0.0 is out now, there now is no default session object, you'll need to instantiate one when needed, assuming you make one during the invocation of the lambda then you should not hit issues with the eventloop stopping.
