### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by fox91** [terrycain/aioboto3#218]
* Async AWS SDK for Python version: `8.2.0`
* Python version: `Python 3.8.5`
* Operating System: `Ubuntu 20.04.1 LTS`

```
aioboto3==8.2.0
aiobotocore==1.1.2
aiohttp==3.7.3
boto3==1.14.44
botocore==1.17.44
```

### Description

I need to download one hundred files from S3 and I'm using `aioboto3`.
After the first 50-60 files (the number also varies from time to time) I get this error for some files:
```
Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACTED: 
Traceback (most recent call last):
  File "/home/ubuntu/ENV/lib/python3.8/site-packages/aiobotocore/utils.py", line 79, in _get_request
    async with session.get(url, headers=headers) as resp:
  File "/home/ubuntu/ENV/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/ENV/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/ubuntu/ENV/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```
repeated many times and than:
```
Max number of attempts exceeded (1) when attempting to retrieve data from metadata service
```

I'm using it in the wrong way or we are hitting some limit of the metadata service?

I think It's related to https://github.com/aio-libs/aiobotocore/issues/808

**Comment by terrycain** [comment]
Hey, this would be an aiobotocore issue if at all.
