### ISSUE TITLE
Is it possible to use S3?

### ISSUE THREAD

**Issue by jiamo** [terrycain/aioboto3#23]
```python
    async with aioboto3.resource('s3', region_name='us-west-1',
                                   #aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   #aws_access_key_id=AWS_ACCESS_KEY_ID
                                 ) as client:
        # upload object to amazon s3
        data = b'\x01'*1024
        resp = await client.put_object(Bucket=bucket,
                                            Key=key,
                                            Body=data)
```

There is error:

```
     AttributeError: 's3.AIOServiceResource' object has no attribute 'put_object'
```

**Comment by terrycain** [comment]
Pretty sure I had that working somewhere, gimme a sec and I'll have a look

**Comment by terrycain** [comment]
Ahh, you should use aioboto3.client

```python
async with aioboto3.client('s3', loop=loop) as client:
    await client.put_object(
        Bucket='testbucket',
        Key='test1',
        Body=b'TestData'
    )
```

The boto S3 Resource only has create_bucket() and get_available_subresources() methods.

**Comment by jiamo** [comment]
Thanks for your quick response. It works.

**Comment by terrycain** [comment]
No problem, be sure to spread the word :smile:, I'm sure there'll be something that doesn't work, but I wont find out until I get lots of people testing it.

**Comment by jiamo** [comment]
Hi. I met a strange problem. I am not  sure it is this package's problem.
I am using localstack to test some s3 func.

`py.test -s test/test_one.py` Work fine. But run the total  `py.test` It will fail.

```
2017-11-07 15:20:37,139 [80424] ERROR sanic(104) Traceback (most recent call last):
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/Users/jiamo/papayafm/papaya-fm/papayafm/api/v1/view.py", line 27, in handle_upload
    data = await upload_file(request)
  File "/Users/jiamo/papayafm/papaya-fm/papayafm/api/v1/test/view.py", line 65, in upload_file
    await s3_put_object(Bucket=s3_bucket, Key="test", Body=result)
  File "/Users/jiamo/papayafm/papaya-fm/papayafm/api/v1/test/view.py", line 54, in s3_put_object
    Bucket=Bucket, Key=Key, Body=Body)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiobotocore/client.py", line 80, in _make_api_call
    operation_model, request_dict)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 313, in _send_request
    exception)):
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 345, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 369, in _get_response
    request.method, request.url, request.headers, request.body)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 290, in _request
    allow_redirects=False)
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiohttp/client.py", line 616, in __iter__
    resp = yield from self._coro
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiohttp/client.py", line 208, in _request
    with timer:
  File "/Users/jiamo/.pyenv/versions/pypayafm/lib/python3.6/site-packages/aiohttp/helpers.py", line 680, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

I using a `py.test --pdb` and using `Boto3` to test
```
(Pdb) s3_client.put_object(Bucket=s3_bucket, Key='test', Body="test")

{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'BaseHTTP/0.6 Python/3.6.3, Werkzeug/0.12.2 Python/3.6.3', 'date': 'Tue, 07 Nov 2017 07:32:30 GMT, Tue, 07 Nov 2017 07:32:30 GMT', 'etag': '"098f6bcd4621d373cade4e832627b4f6"', 'last-modified': 'Tue, 07 Nov 2017 07:32:30 GMT', 'content-length': '233', 'content-type': 'text/html; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent'}, 'RetryAttempts': 0}, 'ETag': '"098f6bcd4621d373cade4e832627b4f6"'}

(Pdb) s3_client.get_object(Bucket=s3_bucket, Key="test")['Body'].read()
b'test'
```

In pdb test with aioboto3. I am not sure is the best method to debug,
```
aio_s3_client = aioboto3.client('s3', endpoint_url="http://localhost:4572")

# I must pass the name as args, otherwise pdb don't find it.
async def debug(aio_s3_client, s3_bucket): await aio_s3_client.put_object(Bucket=s3_bucket, Key='test', Body="aiotest")

(Pdb) loop.run_until_complete(debug(aio_s3_client, s3_bucket))
*** RuntimeError: Timeout context manager should be used inside a task
(The same error py.test tell)

# It return immediately

```

**Comment by terrycain** [comment]
can I get the whole test case

**Comment by jiamo** [comment]
I  re produce it in a more simple case. https://github.com/jiamo/test_app

**Comment by jiamo** [comment]
"The 2nd testcase will be ran in a different event loop" 
While I think the yield_fixture app is in the pytest's  session scope. So all the test time it have only one app and one loop.

From the trackback to the problem it is good example to learn.

**Comment by terrycain** [comment]
If you add the following print statement you'll see it printed twice with 2 different values
```python
@app.listener('before_server_start')
    async def setup(app, loop):
        global s3_client  # not very well but work
        print('Loop: {0}'.format(id(loop)))
```
The reason being is the loop fixture from pytest is function scoped.

**Comment by terrycain** [comment]
hmm, I'll have a look that should exist I think

**Comment by terrycain** [comment]
Ahh, it seems I missed 1 character out of setup.py, https://github.com/terrycain/aioboto3/blob/master/setup.py#L37 should be `aioboto3*` as otherwise it doesnt pick up submodules. Will fix

**Comment by terrycain** [comment]
Should be working in 2.0.1, sorry about that, But now you get s3_client.download_file and s3_client.upload_file in async form now

**Comment by terrycain** [comment]
If you dont mind me asking, what ya using aioboto3 for? (Just trying to get a feel for what parts of aws most people are using)

**Comment by jiamo** [comment]
I have sanic server may write or read the dynamdb or s3. If most function of boto3 can be used `in async way` that will by very helpful.

**Comment by vEpiphyte** [comment]
@terrycain Did you ever upstream your patch for the moto library to support aioboto3?

**Comment by terrycain** [comment]
I dont think i ever got round to it. I generally just run moto in server mode these days and use pytest to deal with the client/resource

**Comment by barakreif** [comment]
so reviving an old issue: we would like to patch the endpoint url for localstack on the session level, not on the client/resource level.

**Comment by terrycain** [comment]
@barakreif I did something similar recently to patch the session object https://github.com/terrycain/aioboto3/blob/master/tests/conftest.py#L89-L115 that might work for you.
