### ISSUE TITLE
SQS (SignatureDoesNotMatch) when calling the ReceiveMessage operation

### ISSUE THREAD

**Issue by Ripeey** [terrycain/aioboto3#326]
* Async AWS SDK for Python version: aioboto3==12.0.0 aiobotocore==2.7.0 
* Python version: 3.11
* Operating System: Debian GNU/Linux 11 (bullseye)

### Description
```[ERROR] 2024-01-14 08:19:05,638:poller - Main thread exception.
Traceback (most recent call last):
  File "poller.py", line 306, in <module>
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "poller.py", line 299, in main
  File "poller.py", line 237, in consumer
  File "aiobotocore/client.py", line 386, in _make_api_call
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ReceiveMessage operation: Signature expired: 20240114T080405Z is now earlier than 20240114T080405Z (20240114T081905Z - 15 min.)
```
For some reason after exact 15 minutes starting my sqs poller am getting this issue. At first i thought my instances were out of sync (time) but it wasnt. Not sure when but my autoscalling instances were getting replaced again and again recently because of this. 

So I ran my poller in my local (ParrotOS 6.0) and I got the exact same error and again exactly after 15 minutes.
![image](https://github.com/terrycain/aioboto3/assets/98874173/9c1025a4-0acd-4535-8c7c-be2c069e9cee)

**Comment by terrycain** [comment]
I'll need a simple example to reproduce this. From a guess, i'd say you were either blocking the event loop for long enough that weird things like this occurs, or perhaps some form of event loop exhaustion where messages have been received but not deserialised by aiobotocore quick enough.
